export interface DashboardData {
    solicitudEDP: string,
    departamento: string,
    municipio: string,
    documentoPropiedad: string,
    actividadDiferente: string,
    grupoEtario: string,
    estadoAbandono: string,
    infraestructuraInstalada: string,
    estadoInfraestructura: string,
    tipoInfraestructura: string,
    inversionInfraestructura: string,
    energiaElectrica: string,
    abasteciomientoAgua: string,
    actividadAdjudicada: string,
    calidadServicioPrestado: string,
    inversionActividades: string,
    user: string,
}